import logging
import time
import uuid
from abc import ABC, abstractmethod
from datetime import datetime, timezone
from typing import List, Dict, Any, Tuple

from sqlalchemy.orm import Session

from app.core.config import settings
from app.models import Meeting, Summary, Topic, ActionItem, TranscriptSegment

logger = logging.getLogger(__name__)

class SummaryGenerator(ABC):
    @abstractmethod
    def generate(self, segments: List[TranscriptSegment]) -> Tuple[str, List[Dict[str, Any]], List[Dict[str, Any]]]:
        """
        Takes a list of transcript segments and returns:
        1. overview (str)
        2. topics (List of dicts with title, start_ms)
        3. action_items (List of dicts with text, source_segment_id)
        """
        pass

class MockSummaryGenerator(SummaryGenerator):
    def generate(self, segments: List[TranscriptSegment]) -> Tuple[str, List[Dict[str, Any]], List[Dict[str, Any]]]:
        if not segments:
            return "No transcript available.", [], []
            
        word_count = sum(len(seg.text.split()) for seg in segments)
        num_segments = len(segments)
        
        overview = f"This is a deterministically generated mock summary. The meeting contained {num_segments} segments and approximately {word_count} words."
        
        # Generate topics based on segments length
        topics = []
        if num_segments > 0:
            topics.append({"title": "Introduction & Kickoff", "start_ms": segments[0].start_ms})
        if num_segments > 5:
            topics.append({"title": "Main Discussion", "start_ms": segments[num_segments // 2].start_ms})
            
        # Extract first-pass action items grounded in segments
        # Look for keywords like "will do", "need to", "action"
        action_items = []
        for seg in segments:
            text_lower = seg.text.lower()
            if "will" in text_lower or "need to" in text_lower or "action" in text_lower:
                action_items.append({
                    "text": f"Follow up on: {seg.text[:50]}...",
                    "source_segment_id": seg.id
                })
                
        # Limit to max 3 mock action items for determinism
        action_items = action_items[:3]
        
        return overview, topics, action_items

class GrokSummaryGenerator(SummaryGenerator):
    """
    Uses xAI's Grok API, which is OpenAI-compatible.
    Requires: pip install openai
    Set LLM_PROVIDER=grok and LLM_API_KEY=xai-... on Render.
    """
    def generate(self, segments: List[TranscriptSegment]) -> Tuple[str, List[Dict[str, Any]], List[Dict[str, Any]]]:
        if not settings.LLM_API_KEY:
            logger.warning("LLM_API_KEY not set. Falling back to mock for Grok.")
            return MockSummaryGenerator().generate(segments)

        try:
            from openai import OpenAI  # openai>=1.0.0

            client = OpenAI(
                api_key=settings.LLM_API_KEY,
                base_url="https://api.x.ai/v1",  # xAI Grok endpoint
            )

            transcript_text = "\n".join(
                f"[{seg.start_ms // 1000}s] {seg.speaker.label if seg.speaker else 'Speaker'}: {seg.text}"
                for seg in segments
            )

            prompt = f"""You are an expert meeting analyst. Given the following meeting transcript, produce:
1. A concise 2-3 sentence overview paragraph.
2. A list of 3-5 key topics discussed (each with a title and the approximate timestamp in milliseconds when it started).
3. A list of concrete action items (each as a short task description).

Return your response as valid JSON in this exact format:
{{
  "overview": "...",
  "topics": [{{"title": "...", "start_ms": 0}}, ...],
  "action_items": [{{"text": "..."}}, ...]
}}

Transcript:
{transcript_text[:8000]}"""

            response = client.chat.completions.create(
                model="grok-3",
                messages=[{"role": "user", "content": prompt}],
                response_format={"type": "json_object"},
                max_tokens=1000,
            )

            import json
            result = json.loads(response.choices[0].message.content)

            overview = result.get("overview", "Summary generated by Grok.")
            topics = result.get("topics", [])
            action_items = result.get("action_items", [])

            # Ensure action_items have source_segment_id = None (Grok doesn't know IDs)
            for ai in action_items:
                ai.setdefault("source_segment_id", None)

            logger.info(f"Grok generated summary: {len(topics)} topics, {len(action_items)} action items.")
            return overview, topics, action_items

        except Exception as e:
            logger.error(f"Grok API call failed: {e}. Falling back to mock.")
            return MockSummaryGenerator().generate(segments)


def get_summary_generator() -> SummaryGenerator:
    provider = settings.LLM_PROVIDER.lower()
    if provider in ("grok", "xai"):
        return GrokSummaryGenerator()
    if provider in ("openai", "anthropic", "llm"):
        return LLMSummaryGenerator()
    return MockSummaryGenerator()

def generate_summary_task(meeting_id: str, db: Session):
    logger.info(f"Starting summary generation for meeting {meeting_id}")
    
    meeting = db.query(Meeting).filter(Meeting.id == meeting_id).first()
    if not meeting:
        logger.error(f"Meeting {meeting_id} not found for summarization.")
        return
        
    meeting.status = "processing"
    db.commit()
    
    # Get segments
    segments = db.query(TranscriptSegment).filter(TranscriptSegment.meeting_id == meeting_id).order_by(TranscriptSegment.sequence_index.asc()).all()
    
    # Generate
    generator = get_summary_generator()
    overview, topics_data, action_items_data = generator.generate(segments)
    
    # Save Summary
    summary = db.query(Summary).filter(Summary.meeting_id == meeting_id).first()
    if not summary:
        summary = Summary(
            id=str(uuid.uuid4()),
            meeting_id=meeting_id,
            overview=overview,
            generated_by="system",
            model_name=settings.LLM_PROVIDER,
            generated_at=datetime.now(timezone.utc),
            status="ready"
        )
        db.add(summary)
    else:
        summary.overview = overview
        summary.status = "ready"
        summary.generated_at = datetime.now(timezone.utc)
        summary.model_name = settings.LLM_PROVIDER
        
    # Overwrite topics
    db.query(Topic).filter(Topic.meeting_id == meeting_id).delete()
    for idx, t_data in enumerate(topics_data):
        topic = Topic(
            id=str(uuid.uuid4()),
            meeting_id=meeting_id,
            title=t_data["title"],
            start_ms=t_data["start_ms"],
            sequence_index=idx
        )
        db.add(topic)
        
    # Insert new action items
    for a_data in action_items_data:
        ai = ActionItem(
            id=str(uuid.uuid4()),
            meeting_id=meeting_id,
            text=a_data["text"],
            source_segment_id=a_data.get("source_segment_id"),
            is_completed=False,
            version=1
        )
        db.add(ai)
        
    # Update meeting status to ready
    meeting.status = "ready"
    db.commit()
    
    logger.info(f"Completed summary generation for meeting {meeting_id}")
