"""Initial schema — all tables + FTS5 virtual table

Revision ID: 0001
Revises: 
Create Date: 2026-08-13 00:00:00.000000

This migration is hand-written (not autogenerated) because:
1. SQLite FTS5 virtual tables cannot be represented in SQLAlchemy ORM
   and therefore cannot be autogenerated by Alembic.
2. We want a single clean migration for the initial schema rather than
   a messy autogenerate diff on an empty database.

All DDL is derived verbatim from the SQL schema in the design doc.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ── users ─────────────────────────────────────────────────────────────────
    op.create_table(
        "users",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), unique=True, nullable=False),
        sa.Column("avatar_url", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
    )

    # ── meetings ──────────────────────────────────────────────────────────────
    op.create_table(
        "meetings",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column(
            "owner_id",
            sa.String(),
            sa.ForeignKey("users.id"),
            nullable=False,
        ),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("meeting_date", sa.TIMESTAMP(), nullable=False),
        sa.Column("duration_seconds", sa.Integer(), default=0, nullable=False),
        sa.Column("media_url", sa.String(), nullable=True),
        sa.Column("media_type", sa.String(), default="audio", nullable=False),
        sa.Column("status", sa.String(), default="ready", nullable=False),
        sa.Column("source", sa.String(), default="upload", nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
    )

    # ── participants ──────────────────────────────────────────────────────────
    op.create_table(
        "participants",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
    )

    # ── meeting_participants (junction) ───────────────────────────────────────
    op.create_table(
        "meeting_participants",
        sa.Column(
            "meeting_id",
            sa.String(),
            sa.ForeignKey("meetings.id", ondelete="CASCADE"),
            primary_key=True,
            nullable=False,
        ),
        sa.Column(
            "participant_id",
            sa.String(),
            sa.ForeignKey("participants.id", ondelete="CASCADE"),
            primary_key=True,
            nullable=False,
        ),
        sa.Column("role", sa.String(), default="attendee", nullable=False),
    )

    # ── speakers ──────────────────────────────────────────────────────────────
    op.create_table(
        "speakers",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column(
            "meeting_id",
            sa.String(),
            sa.ForeignKey("meetings.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("color_hex", sa.String(), default="#6C5CE7", nullable=False),
    )

    # ── transcript_segments ───────────────────────────────────────────────────
    op.create_table(
        "transcript_segments",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column(
            "meeting_id",
            sa.String(),
            sa.ForeignKey("meetings.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "speaker_id",
            sa.String(),
            sa.ForeignKey("speakers.id"),
            nullable=True,
        ),
        sa.Column("sequence_index", sa.Integer(), nullable=False),
        sa.Column("start_ms", sa.Integer(), nullable=False),
        sa.Column("end_ms", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
    )

    # Composite indexes from the design doc schema
    op.create_index(
        "idx_segments_meeting",
        "transcript_segments",
        ["meeting_id", "sequence_index"],
    )
    op.create_index(
        "idx_segments_time",
        "transcript_segments",
        ["meeting_id", "start_ms"],
    )

    # ── FTS5 virtual table ────────────────────────────────────────────────────
    # SQLite FTS5 cannot be expressed as an ORM model; created via raw DDL.
    # content= links it to transcript_segments so FTS index is auto-updated on
    # INSERT/UPDATE/DELETE via triggers (added below).
    op.execute(
        """
        CREATE VIRTUAL TABLE transcript_segments_fts
        USING fts5(
            text,
            content='transcript_segments',
            content_rowid='rowid'
        )
        """
    )

    # Triggers to keep the FTS index in sync with the content table.
    op.execute(
        """
        CREATE TRIGGER ts_fts_insert AFTER INSERT ON transcript_segments BEGIN
            INSERT INTO transcript_segments_fts(rowid, text)
            VALUES (new.rowid, new.text);
        END
        """
    )
    op.execute(
        """
        CREATE TRIGGER ts_fts_delete AFTER DELETE ON transcript_segments BEGIN
            INSERT INTO transcript_segments_fts(transcript_segments_fts, rowid, text)
            VALUES ('delete', old.rowid, old.text);
        END
        """
    )
    op.execute(
        """
        CREATE TRIGGER ts_fts_update AFTER UPDATE ON transcript_segments BEGIN
            INSERT INTO transcript_segments_fts(transcript_segments_fts, rowid, text)
            VALUES ('delete', old.rowid, old.text);
            INSERT INTO transcript_segments_fts(rowid, text)
            VALUES (new.rowid, new.text);
        END
        """
    )

    # ── summaries ─────────────────────────────────────────────────────────────
    op.create_table(
        "summaries",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column(
            "meeting_id",
            sa.String(),
            sa.ForeignKey("meetings.id", ondelete="CASCADE"),
            unique=True,
            nullable=False,
        ),
        sa.Column("overview", sa.String(), nullable=True),
        sa.Column("generated_by", sa.String(), default="mock", nullable=False),
        sa.Column("model_name", sa.String(), nullable=True),
        sa.Column("generated_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("status", sa.String(), default="pending", nullable=False),
    )

    # ── topics ────────────────────────────────────────────────────────────────
    op.create_table(
        "topics",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column(
            "meeting_id",
            sa.String(),
            sa.ForeignKey("meetings.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("start_ms", sa.Integer(), nullable=True),
        sa.Column("sequence_index", sa.Integer(), nullable=False),
    )

    # ── action_items ──────────────────────────────────────────────────────────
    op.create_table(
        "action_items",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column(
            "meeting_id",
            sa.String(),
            sa.ForeignKey("meetings.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column(
            "assignee_id",
            sa.String(),
            sa.ForeignKey("participants.id"),
            nullable=True,
        ),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("is_completed", sa.Boolean(), default=False, nullable=False),
        sa.Column(
            "source_segment_id",
            sa.String(),
            sa.ForeignKey("transcript_segments.id"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
    )

    # ── tags ──────────────────────────────────────────────────────────────────
    op.create_table(
        "tags",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("name", sa.String(), unique=True, nullable=False),
    )

    # ── meeting_tags (junction) ───────────────────────────────────────────────
    op.create_table(
        "meeting_tags",
        sa.Column(
            "meeting_id",
            sa.String(),
            sa.ForeignKey("meetings.id", ondelete="CASCADE"),
            primary_key=True,
            nullable=False,
        ),
        sa.Column(
            "tag_id",
            sa.String(),
            sa.ForeignKey("tags.id", ondelete="CASCADE"),
            primary_key=True,
            nullable=False,
        ),
    )

    # ── annotations ───────────────────────────────────────────────────────────
    op.create_table(
        "annotations",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column(
            "meeting_id",
            sa.String(),
            sa.ForeignKey("meetings.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "segment_id",
            sa.String(),
            sa.ForeignKey("transcript_segments.id", ondelete="CASCADE"),
            nullable=True,
        ),
        sa.Column(
            "author_id",
            sa.String(),
            sa.ForeignKey("users.id"),
            nullable=True,
        ),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("body", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
    )


def downgrade() -> None:
    # Drop in reverse order of creation (respect FK constraints)
    op.drop_table("annotations")
    op.drop_table("meeting_tags")
    op.drop_table("tags")
    op.drop_table("action_items")
    op.drop_table("topics")
    op.drop_table("summaries")

    # Drop FTS triggers and virtual table
    op.execute("DROP TRIGGER IF EXISTS ts_fts_update")
    op.execute("DROP TRIGGER IF EXISTS ts_fts_delete")
    op.execute("DROP TRIGGER IF EXISTS ts_fts_insert")
    op.execute("DROP TABLE IF EXISTS transcript_segments_fts")

    op.drop_index("idx_segments_time", table_name="transcript_segments")
    op.drop_index("idx_segments_meeting", table_name="transcript_segments")
    op.drop_table("transcript_segments")
    op.drop_table("speakers")
    op.drop_table("meeting_participants")
    op.drop_table("participants")
    op.drop_table("meetings")
    op.drop_table("users")
